const translations: Record<string, Record<string, Record<string, string>>> = {
  en: {
    nav: { dashboard: 'Dashboard', members: 'Members', revenue: 'Revenue', plans: 'Plans', services: 'Services', reports: 'Reports', expenses: 'Expenses', branches: 'Branches', settings: 'Settings', scan: 'Scan QR', logout: 'Sign Out', lang: 'العربية' },
    common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', confirm: 'Confirm', loading: 'Loading...', noData: 'No data', search: 'Search...', filter: 'Filter', export: 'Export', actions: 'Actions', back: 'Back', close: 'Close', all: 'All', active: 'Active', expired: 'Expired', frozen: 'Frozen', day: 'day', days: 'days', select: 'Select...', error: 'An error occurred', download: 'Download', print: 'Print' },
    status: { active: 'Active', expiring_soon: 'Expiring Soon', expired: 'Expired', paused: 'Paused', frozen: 'Frozen' },
    dashboard: { title: 'Dashboard', subtitle: "Here's what's happening today at your gym.", totalMembers: 'Total Members', activeSubs: 'Active Subscriptions', expiringSoon: 'Expiring Soon', expired: 'Expired', todayRevenue: "Today's Revenue", thisMonth: 'This Month', totalRevenue: 'Total Revenue', activeRate: 'Active Rate', monthlyRevenue: 'Monthly Revenue', membershipDist: 'Membership Distribution', addMember: 'Add Member', viewMembers: 'View Members' },
    members: { title: 'Members', subtitle: 'Manage your gym members', total: 'Total members', add: 'Add Member', noResults: 'No members found', empty: 'No members yet', search: 'Search members...', phone: 'Phone', age: 'Age', weight: 'Weight', height: 'Height', gender: 'Gender', fullName: 'Full Name', created: 'Created', plan: 'Plan', endDate: 'End Date', daysLeft: 'days left', deleteConfirm: 'Delete Member', deleteMsg: 'Are you sure you want to delete this member? This action cannot be undone.', noPlan: 'No Plan' },
    member: { title: 'Member Profile', notFound: 'Member not found', noId: 'No member ID provided', back: 'Back to Members', subscription: 'Subscription', startDate: 'Start Date', endDate: 'End Date', planPrice: 'Plan Price', services: 'Services', extraServices: 'Extra Services', totalPaid: 'Total Paid', paymentHistory: 'Payment History', date: 'Date', amount: 'Amount', type: 'Type', method: 'Method', notes: 'Notes', edit: 'Edit Member', renew: 'Renew Subscription', freeze: 'Freeze Subscription', unfreeze: 'Unfreeze', weight: 'Weight', height: 'Height', memberSince: 'Member Since', freezeReason: 'Freeze Reason', freezeHistory: 'Freeze History', freezeSuccess: 'Subscription frozen successfully', unfreezeSuccess: 'Subscription unfrozen successfully', freezeFeeLabel: 'Freeze Fee' },
    revenue: { title: 'Revenue', subtitle: "Track your gym's financial performance", today: "Today's Revenue", week: 'This Week', month: 'This Month', year: 'This Year', total: 'Total Revenue', revenueOverTime: 'Revenue Over Time', revenueByPlan: 'Revenue by Plan', recentTransactions: 'Recent Transactions' },
    plans: { title: 'Plans', subtitle: 'Manage subscription plans', total: 'Total plans', add: 'Add Plan', empty: 'No plans yet', name: 'Plan Name', duration: 'Duration (days)', price: 'Price', description: 'Description', color: 'Color', edit: 'Edit Plan', deleteConfirm: 'Delete Plan', saved: 'Plan saved', deleted: 'Plan deleted' },
    services: { title: 'Services', subtitle: 'Manage extra services', total: 'Total services', add: 'Add Service', empty: 'No services yet', name: 'Service Name', price: 'Price', description: 'Description', edit: 'Edit Service', deleteConfirm: 'Delete Service', saved: 'Service saved', deleted: 'Service deleted' },
    reports: { title: 'Reports', subtitle: 'Generate and export reports', members: 'Members Report', membersDesc: 'View all registered members data', revenue: 'Revenue Report', revenueDesc: 'View all payment transactions', expiring: 'Expiring Members', expiringDesc: 'View members with expiring subscriptions', subscriptions: 'Subscriptions Report', profitLoss: 'Profit & Loss', totalRevenue: 'Total Revenue', totalExpenses: 'Total Expenses', netProfit: 'Net Profit', exportCSV: 'Export CSV', exportExcel: 'Export Excel', exportPDF: 'Export PDF' },
    expenses: { title: 'Expenses', subtitle: 'Track your gym expenses', total: 'Total expenses', add: 'Add Expense', history: 'Expense History', description: 'Description', amount: 'Amount', category: 'Category', date: 'Date', method: 'Payment Method', bankTransfer: 'Bank Transfer' },
    branches: { title: 'Branches', subtitle: 'Manage gym branches', total: 'Total branches', add: 'Add Branch', empty: 'No branches yet', name: 'Branch Name', address: 'Address', phone: 'Phone', deleteConfirm: 'Delete Branch', saved: 'Branch saved', deleted: 'Branch deleted' },
    settings: { title: 'Settings', subtitle: 'Manage your gym settings', general: 'General Settings', gymName: 'Gym Name', currency: 'Currency', phone: 'Phone', address: 'Address', save: 'Save Settings', saved: 'Settings saved successfully', appearance: 'Appearance', theme: 'Theme', dark: 'Dark', light: 'Light', account: 'Account', signOut: 'Sign Out' },
    scan: { title: 'Scan QR', subtitle: 'Scan member QR code to check in', start: 'Start Scanning', stop: 'Stop Scanning', scanning: 'Scanning...', placeholder: 'Point camera at QR code', cameraError: 'Camera access denied or not available', success: 'Checked in successfully', alreadyCheckedIn: 'Already checked in today', invalid: 'Invalid QR code', notFound: 'Member not found', error: 'Check-in failed' },
    addMember: { title: 'Add Member', subtitle: 'Register a new member', name: 'Full Name', age: 'Age', phone: 'Phone', gender: 'Gender', male: 'Male', female: 'Female', weight: 'Weight', height: 'Height', notes: 'Notes', photo: 'Photo', photoHint: 'Optional: Upload a profile photo', personalInfo: 'Personal Information', membership: 'Membership Details', plan: 'Plan', selectPlan: 'Select a plan', startDate: 'Start Date', extraServices: 'Extra Services', planPrice: 'Plan Price', servicesTotal: 'Services Total', total: 'Total', save: 'Save Member', cancel: 'Cancel' },
    editMember: { title: 'Edit Member', subtitle: 'Update member information' },
    login: { title: 'Sign In', subtitle: 'Sign in to manage your gym', email: 'Email', password: 'Password', signIn: 'Sign In', error: 'Invalid email or password' },
    attendance: { success: 'Checked in successfully' },
  },
  ar: {
    nav: { dashboard: 'لوحة التحكم', members: 'الأعضاء', revenue: 'الإيرادات', plans: 'الباقات', services: 'الخدمات', reports: 'التقارير', expenses: 'المصروفات', branches: 'الفروع', settings: 'الإعدادات', scan: 'مسح QR', logout: 'تسجيل الخروج', lang: 'English' },
    common: { save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', confirm: 'تأكيد', loading: 'جاري التحميل...', noData: 'لا توجد بيانات', search: 'بحث...', filter: 'تصفية', export: 'تصدير', actions: 'إجراءات', back: 'رجوع', close: 'إغلاق', all: 'الكل', active: 'نشط', expired: 'منتهي', frozen: 'مجمّد', day: 'يوم', days: 'أيام', select: 'اختر...', error: 'حدث خطأ', download: 'تحميل', print: 'طباعة' },
    status: { active: 'نشط', expiring_soon: 'ينتهي قريباً', expired: 'منتهي', paused: 'متوقف', frozen: 'مجمّد' },
    dashboard: { title: 'لوحة التحكم', subtitle: 'إليك ما يحدث اليوم في صالتك.', totalMembers: 'إجمالي الأعضاء', activeSubs: 'اشتراكات نشطة', expiringSoon: 'تنتهي قريباً', expired: 'منتهية', todayRevenue: 'إيرادات اليوم', thisMonth: 'هذا الشهر', totalRevenue: 'إجمالي الإيرادات', activeRate: 'نسبة النشاط', monthlyRevenue: 'الإيرادات الشهرية', membershipDist: 'توزيع العضويات', addMember: 'إضافة عضو', viewMembers: 'عرض الأعضاء' },
    members: { title: 'الأعضاء', subtitle: 'إدارة أعضاء الصالة', total: 'إجمالي الأعضاء', add: 'إضافة عضو', noResults: 'لم يتم العثور على أعضاء', empty: 'لا يوجد أعضاء بعد', search: 'بحث عن أعضاء...', phone: 'الهاتف', age: 'العمر', weight: 'الوزن', height: 'الطول', gender: 'الجنس', fullName: 'الاسم الكامل', created: 'تاريخ التسجيل', plan: 'الباقة', endDate: 'تاريخ الانتهاء', daysLeft: 'أيام متبقية', deleteConfirm: 'حذف العضو', deleteMsg: 'هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء.', noPlan: 'لا توجد باقة' },
    member: { title: 'الملف الشخصي', notFound: 'لم يتم العثور على العضو', noId: 'لم يتم توفير معرف العضو', back: 'رجوع للأعضاء', subscription: 'الاشتراك', startDate: 'تاريخ البداية', endDate: 'تاريخ الانتهاء', planPrice: 'سعر الباقة', services: 'الخدمات', extraServices: 'خدمات إضافية', totalPaid: 'الإجمالي المدفوع', paymentHistory: 'سجل المدفوعات', date: 'التاريخ', amount: 'المبلغ', type: 'النوع', method: 'طريقة الدفع', notes: 'ملاحظات', edit: 'تعديل العضو', renew: 'تجديد الاشتراك', freeze: 'تجميد الاشتراك', unfreeze: 'إلغاء التجميد', weight: 'الوزن', height: 'الطول', memberSince: 'عضو منذ', freezeReason: 'سبب التجميد', freezeHistory: 'سجل التجميد', freezeSuccess: 'تم تجميد الاشتراك بنجاح', unfreezeSuccess: 'تم إلغاء تجميد الاشتراك بنجاح', freezeFeeLabel: 'رسوم التجميد' },
    revenue: { title: 'الإيرادات', subtitle: 'تتبع الأداء المالي لصالتك', today: 'إيرادات اليوم', week: 'هذا الأسبوع', month: 'هذا الشهر', year: 'هذا العام', total: 'إجمالي الإيرادات', revenueOverTime: 'الإيرادات على مدار الوقت', revenueByPlan: 'الإيرادات حسب الباقة', recentTransactions: 'آخر المعاملات' },
    plans: { title: 'الباقات', subtitle: 'إدارة باقات الاشتراك', total: 'إجمالي الباقات', add: 'إضافة باقة', empty: 'لا توجد باقات بعد', name: 'اسم الباقة', duration: 'المدة (أيام)', price: 'السعر', description: 'الوصف', color: 'اللون', edit: 'تعديل الباقة', deleteConfirm: 'حذف الباقة', saved: 'تم حفظ الباقة', deleted: 'تم حذف الباقة' },
    services: { title: 'الخدمات', subtitle: 'إدارة الخدمات الإضافية', total: 'إجمالي الخدمات', add: 'إضافة خدمة', empty: 'لا توجد خدمات بعد', name: 'اسم الخدمة', price: 'السعر', description: 'الوصف', edit: 'تعديل الخدمة', deleteConfirm: 'حذف الخدمة', saved: 'تم حفظ الخدمة', deleted: 'تم حذف الخدمة' },
    reports: { title: 'التقارير', subtitle: 'إنشاء وتصدير التقارير', members: 'تقرير الأعضاء', membersDesc: 'عرض بيانات جميع الأعضاء المسجلين', revenue: 'تقرير الإيرادات', revenueDesc: 'عرض جميع معاملات الدفع', expiring: 'الأعضاء المنتهية صلاحيتهم', expiringDesc: 'عرض الأعضاء الذين تنتهي صلاحية اشتراكاتهم', subscriptions: 'تقرير الاشتراكات', profitLoss: 'الأرباح والخسائر', totalRevenue: 'إجمالي الإيرادات', totalExpenses: 'إجمالي المصروفات', netProfit: 'صافي الربح', exportCSV: 'تصدير CSV', exportExcel: 'تصدير Excel', exportPDF: 'تصدير PDF' },
    expenses: { title: 'المصروفات', subtitle: 'تتبع مصروفات الصالة', total: 'إجمالي المصروفات', add: 'إضافة مصروف', history: 'سجل المصروفات', description: 'الوصف', amount: 'المبلغ', category: 'التصنيف', date: 'التاريخ', method: 'طريقة الدفع', bankTransfer: 'تحويل بنكي' },
    branches: { title: 'الفروع', subtitle: 'إدارة فروع الصالة', total: 'إجمالي الفروع', add: 'إضافة فرع', empty: 'لا توجد فروع بعد', name: 'اسم الفرع', address: 'العنوان', phone: 'الهاتف', deleteConfirm: 'حذف الفرع', saved: 'تم حفظ الفرع', deleted: 'تم حذف الفرع' },
    settings: { title: 'الإعدادات', subtitle: 'إدارة إعدادات الصالة', general: 'الإعدادات العامة', gymName: 'اسم الصالة', currency: 'العملة', phone: 'الهاتف', address: 'العنوان', save: 'حفظ الإعدادات', saved: 'تم حفظ الإعدادات بنجاح', appearance: 'المظهر', theme: 'السمة', dark: 'داكن', light: 'فاتح', account: 'الحساب', signOut: 'تسجيل الخروج' },
    scan: { title: 'مسح QR', subtitle: 'امسح رمز QR للعضو لتسجيل الحضور', start: 'بدء المسح', stop: 'إيقاف المسح', scanning: 'جاري المسح...', placeholder: 'وجّه الكاميرا نحو رمز QR', cameraError: 'تعذر الوصول إلى الكاميرا', success: 'تم تسجيل الحضور بنجاح', alreadyCheckedIn: 'تم تسجيل الحضور مسبقاً اليوم', invalid: 'رمز QR غير صالح', notFound: 'لم يتم العثور على العضو', error: 'فشل تسجيل الحضور' },
    addMember: { title: 'إضافة عضو', subtitle: 'تسجيل عضو جديد', name: 'الاسم الكامل', age: 'العمر', phone: 'الهاتف', gender: 'الجنس', male: 'ذكر', female: 'أنثى', weight: 'الوزن', height: 'الطول', notes: 'ملاحظات', photo: 'صورة', photoHint: 'اختياري: تحميل صورة شخصية', personalInfo: 'معلومات شخصية', membership: 'تفاصيل الاشتراك', plan: 'الباقة', selectPlan: 'اختر باقة', startDate: 'تاريخ البداية', extraServices: 'خدمات إضافية', planPrice: 'سعر الباقة', servicesTotal: 'إجمالي الخدمات', total: 'المجموع', save: 'حفظ العضو', cancel: 'إلغاء' },
    editMember: { title: 'تعديل العضو', subtitle: 'تحديث بيانات العضو' },
    login: { title: 'تسجيل الدخول', subtitle: 'سجل الدخول لإدارة صالتك', email: 'البريد الإلكتروني', password: 'كلمة المرور', signIn: 'تسجيل الدخول', error: 'بريد إلكتروني أو كلمة مرور غير صحيحة' },
    attendance: { success: 'تم تسجيل الحضور بنجاح' },
  },
}

export function t(key: string, lang: string): string {
  const keys = key.split('.')
  let val: unknown = translations[lang]
  for (const k of keys) {
    if (!val || typeof val !== 'object') return key
    val = (val as Record<string, unknown>)[k]
  }
  return (val !== undefined && val !== null ? String(val) : key)
}
